### ISSUE TITLE
Possible OverflowError from dateutil is ignored.

### ISSUE THREAD

**Issue by Dunes** [akoumjian/datefinder#100]
See https://stackoverflow.com/questions/54465029/overflowerror-when-trying-to-convert-generators-to-lists/54478879#54478879

Steps to reproduce:

```python
>>> list(datefinder.find_dates("2019/02/01 is a date and 466990103060049 is not"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/datefinder/__init__.py", line 31, in find_dates
    as_dt = self.parse_date_string(date_string, captures)
  File "/usr/local/lib/python3.5/dist-packages/datefinder/__init__.py", line 101, in parse_date_string
    as_dt = parser.parse(date_string, default=self.base_date)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser.py", line 1182, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/dateutil/parser.py", line 578, in parse
    if cday > monthrange(cyear, cmonth)[1]:
  File "/usr/lib/python3.5/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/usr/lib/python3.5/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()
OverflowError: signed integer is greater than maximum
```

Expected result:

```python
[datetime.datetime(2019, 2, 1, 0, 0)]
```

**Comment by danielsnider** [comment]
Same problem for me.

**Comment by diannamcallister** [comment]
Same problem for me.

**Comment by danielsnider** [comment]
Hi @diannamcallister,

Could you post the diff of the fix that we found worked? Adding the
exception catching?

Thanks!
Daniel Snider ツ

**Comment by akoumjian** [comment]
Maintainer note: this comment/action is being posted by Codex AI agent at Alec Koumjian's direction.

Thank you for taking the time to report this.

As part of the 1.0.0rc3 release-candidate triage, we're closing older pre-v2 backlog reports to reset against the rewritten parser.

If this still reproduces on datefinder==1.0.0rc3, please reply with:
- exact Python version
- minimal input string
- expected output
- actual output

We'll reopen immediately on a confirmed repro.

Quick retest command:
  pip install --upgrade pip
  pip install --pre "datefinder==1.0.0rc3"

Thank you again for your time and contribution.
