### ISSUE TITLE
RuntimeError: invalid RE code

### ISSUE THREAD

**Issue by VijayaLakshmiArthanari** [akoumjian/datefinder#110]
Traceback (most recent call last):

  File "<ipython-input-1-e5fe3d7a8675>", line 1, in <module>
    runfile('D:/Resume_ProperCode(3.6)/Main_Code.py', wdir='D:/Resume_ProperCode(3.6)')

  File "D:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "D:\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Resume_ProperCode(3.6)/Main_Code.py", line 25, in <module>
    from Get_DOB import get_DOB

  File "D:\Resume_ProperCode(3.6)\Get_DOB.py", line 4, in <module>
    import datefinder

  File "D:\Anaconda3\lib\site-packages\datefinder\__init__.py", line 6, in <module>
    from .constants import (

  File "D:\Anaconda3\lib\site-packages\datefinder\constants.py", line 138, in <module>
    DATES_PATTERN, re.IGNORECASE | re.MULTILINE | re.UNICODE | re.DOTALL | re.VERBOSE

  File "D:\Anaconda3\lib\site-packages\regex.py", line 345, in compile
    return _compile(pattern, flags, kwargs)

  File "D:\Anaconda3\lib\site-packages\regex.py", line 607, in _compile
    req_offset, req_chars, req_flags, info.group_count)

RuntimeError: invalid RE code

Error While importing the 'datefinder' package

**Comment by VijayaLakshmiArthanari** [comment]
I was solved my issue by just updating the regex module from 2.4.120 to 2.5.64 . It was solved this issue

**Comment by akoumjian** [comment]
Maintainer note: this comment/action is being posted by Codex AI agent at Alec Koumjian's direction.

Thank you for taking the time to report this.

As part of the 1.0.0rc3 release-candidate triage, we're closing older pre-v2 backlog reports to reset against the rewritten parser.

If this still reproduces on datefinder==1.0.0rc3, please reply with:
- exact Python version
- minimal input string
- expected output
- actual output

We'll reopen immediately on a confirmed repro.

Quick retest command:
  pip install --upgrade pip
  pip install --pre "datefinder==1.0.0rc3"

Thank you again for your time and contribution.
