### ISSUE TITLE
OverflowError: signed integer is greater than maximum

### ISSUE THREAD

**Issue by macdonjo** [akoumjian/datefinder#115]
Having an issue reading a large HTML file for a date.

`Traceback (most recent call last):
  File "scraper.py", line 142, in <module>
    matches = list(datefinder.find_dates(todayHtml))
  File "/Users/user/anaconda/lib/python2.7/site-packages/datefinder/__init__.py", line 31, in find_dates
    as_dt = self.parse_date_string(date_string, captures)
  File "/Users/user/anaconda/lib/python2.7/site-packages/datefinder/__init__.py", line 101, in parse_date_string
    as_dt = parser.parse(date_string, default=self.base_date)
  File "/Users/user/anaconda/lib/python2.7/site-packages/dateutil/parser.py", line 1168, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/dateutil/parser.py", line 578, in parse
    if cday > monthrange(cyear, cmonth)[1]:
  File "/Users/user/anaconda/lib/python2.7/calendar.py", line 121, in monthrange
    day1 = weekday(year, month, 1)
  File "/Users/user/anaconda/lib/python2.7/calendar.py", line 113, in weekday
    return datetime.date(year, month, day).weekday()`

**Comment by mklaber** [comment]
This issue will happen when the input contains a UK phone number. For example:

```python
s = r"""John Smith
07111222333
john.smith@domain.com"""
next(datefinder.find_dates(s))
```

Yields:

```
mypath/lib/python3.6/calendar.py in weekday(year, month, day)
    114     """Return weekday (0-6 ~ Mon-Sun) for year (1970-...), month (1-12),
    115        day (1-31)."""
--> 116     return datetime.date(year, month, day).weekday()
    117 
    118 

OverflowError: signed integer is greater than maximum
```

**Comment by rakeshravidata** [comment]
Has anybody found a foxi for this? Facing the same error

**Comment by akoumjian** [comment]
Maintainer note: this comment/action is being posted by Codex AI agent at Alec Koumjian's direction.

Thank you for taking the time to report this.

As part of the 1.0.0rc3 release-candidate triage, we're closing older pre-v2 backlog reports to reset against the rewritten parser.

If this still reproduces on datefinder==1.0.0rc3, please reply with:
- exact Python version
- minimal input string
- expected output
- actual output

We'll reopen immediately on a confirmed repro.

Quick retest command:
  pip install --upgrade pip
  pip install --pre "datefinder==1.0.0rc3"

Thank you again for your time and contribution.
