### ISSUE TITLE
dateutil.parser.parse throws ValueError on crud date strings

### ISSUE THREAD

**Issue by thebigspoon** [akoumjian/datefinder#17]
Issue #14 highlights we need to wrap `dateutil.parser.parse`:
```python
>>> from dateutil import parser
>>> parser.parse('to blah')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/src/datefinder/venv/lib/python3.4/site-packages/python_dateutil-2.4.2-py3.4.egg/dateutil/parser.py", line 1008, in parse
  File "/usr/local/src/datefinder/venv/lib/python3.4/site-packages/python_dateutil-2.4.2-py3.4.egg/dateutil/parser.py", line 395, in parse
ValueError: Unknown string format
```
Fixed and added a passing test in [this draft implementation](https://github.com/thebigspoon/datefinder/blob/14_extra_tokens/tests/test_parse_date_string.py#L42-L50)

**Comment by akoumjian** [comment]
Theoretically we shouldn't be passing dateutil bad datetime strings. Not sure if this issue is ready to close or not.

**Comment by thebigspoon** [comment]
@akoumjian: yep, that was in the PR #19 thanks! We agreed to let it bubble
