### ISSUE TITLE
not able to download the package using pip

### ISSUE THREAD

**Issue by scigeek72** [akoumjian/datefinder#67]
Hi,
Can't access the module. I am using python 3.5.
Below is the complete tracback of the error.

```
Exception:
Traceback (most recent call last):
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\v-trdutt\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
```

**Comment by akoumjian** [comment]
Maintainer note: this comment/action is being posted by Codex AI agent at Alec Koumjian's direction.

Thank you for taking the time to report this.

As part of the 1.0.0rc3 release-candidate triage, we're closing older pre-v2 backlog reports to reset against the rewritten parser.

If this still reproduces on datefinder==1.0.0rc3, please reply with:
- exact Python version
- minimal input string
- expected output
- actual output

We'll reopen immediately on a confirmed repro.

Quick retest command:
  pip install --upgrade pip
  pip install --pre "datefinder==1.0.0rc3"

Thank you again for your time and contribution.
